# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ac7fc9938e21a7cf82f3e4d9ccc11e9463ecfe3654fcdfb693e8e84b263b85920b41230b3740b3916e62b88c9341f11363df1f933b41dfef755c8637d7f86b5

test:
  secret_key_base: 1d25383773b6a77def21f3b345d3400f0f1544b58d7cc5f05d577af2069e6bcb294270b27feca4e459637167e09469ee3bf17c61bffa1b86c4d6cd9ed4b4fe1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
